name: NEXT Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Setup .env
        run: |
          echo MONGODB_URI=${{ secrets.MONGODB_URI }}
          echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env
          echo NEXT_AUTH_ISSUER=${{ secrets.NEXT_AUTH_ISSUER }} >> .env
          echo NEXT_PUBLIC_AWS_BUCKET_NAME=${{ secrets.NEXT_PUBLIC_AWS_BUCKET_NAME }} >> .env
          echo AWS_CLOUDFRONT_URL=${{ secrets.AWS_CLOUDFRONT_URL }} >> .env
          echo NEXT_PUBLIC_AWS_REGION=${{ secrets.NEXT_PUBLIC_AWS_REGION }} >> .env
          echo NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY=${{ secrets.NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY }} >> .env
          echo NEXT_PUBLIC_AWS_ACCESS_KEY_ID=${{ secrets.NEXT_PUBLIC_AWS_ACCESS_KEY_ID }} >> .env
          echo NODE_ENV=production >> .env
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test --if-present